[package]
name = "costanalytics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.2"
tesseract = "0.15.1"
tesseract-plumbing = "0.9.0"
